name: Build ElementaMine

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Java 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'

      - name: Verifier la version Java active
        run: |
          echo "JAVA_HOME = $JAVA_HOME"
          java -version
          javac -version

      - name: Compilation avec Maven
        run: mvn -B clean package

      - name: Upload du plugin compile
        uses: actions/upload-artifact@v4
        with:
          name: ElementaMine
          path: target/ElementaMine.jar
